create table MSPR_DECHET_DEPOT
(
    ID        NUMBER(5) not null
        constraint PK_DECHET_DEPOT
            primary key,
    ID_DEPOT  NUMBER(5) not null
        constraint FK_DEPOT_DECHET_DEPOT
            references MSPR_DEPOT,
    ID_DECHET NUMBER(5) not null
        constraint FK_DECHET_DECHET_DEPOT
            references MSPR_DECHET,
    QUANTITE  NUMBER(9) not null
)
/

INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (1, 1, 1, 200);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (2, 2, 2, 120);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (3, 3, 4, 55);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (4, 4, 12, 60);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (5, 5, 8, 50);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (6, 6, 6, 15);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (7, 7, 11, 35);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (8, 8, 1, 155);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (9, 9, 12, 10);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (10, 10, 11, 30);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (11, 11, 2, 200);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (12, 12, 2, 70);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (13, 13, 1, 215);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (14, 14, 12, 32);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (15, 15, 2, 170);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (16, 16, 4, 120);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (17, 17, 1, 60);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (18, 18, 3, 50);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (19, 19, 6, 10);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (20, 20, 7, 50);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (21, 21, 7, 20);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (22, 22, 6, 20);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (23, 23, 1, 120);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (24, 24, 6, 10);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (25, 25, 1, 150);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (26, 26, 6, 12);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (27, 27, 8, 40);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (28, 28, 2, 60);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (29, 29, 7, 20);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (30, 30, 4, 40);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (31, 31, 11, 55);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (32, 32, 7, 100);
INSERT INTO SYSTEM.MSPR_DECHET_DEPOT (ID, ID_DEPOT, ID_DECHET, QUANTITE) VALUES (33, 33, 1, 120);