create table MSPR_DETAIL_DEMANDE_DECHET
(
    ID                    NUMBER(5) not null
        constraint PK_DETAIL_DEMANDE_DECHET
            primary key,
    ID_DEMANDE_ENLEVEMENT NUMBER(5) not null
        constraint FK_DEMANDE_ENLEVEMENT_DETAIL_DEMANDE_DECHET
            references MSPR_DEMANDE_ENLEVEMENT,
    ID_DECHET             NUMBER(5) not null
        constraint FK_DECHET_DETAIL_DEMANDE_DECHET
            references MSPR_DECHET,
    QUANTITE              NUMBER(9) not null
)
/

INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (1, 1, 1, 120);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (2, 1, 3, 50);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (3, 2, 2, 50);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (4, 3, 6, 15);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (5, 4, 1, 55);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (6, 5, 12, 10);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (7, 6, 12, 12);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (8, 6, 1, 100);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (9, 6, 2, 20);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (10, 7, 2, 50);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (11, 8, 1, 60);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (12, 9, 6, 10);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (13, 10, 3, 50);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (14, 10, 2, 50);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (15, 11, 1, 60);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (16, 12, 6, 10);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (17, 13, 7, 20);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (18, 14, 1, 50);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (19, 15, 2, 60);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (20, 15, 7, 20);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (21, 16, 11, 55);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (22, 17, 4, 20);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (23, 18, 2, 20);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (24, 18, 8, 50);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (25, 18, 12, 60);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (26, 19, 1, 100);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (27, 20, 2, 200);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (28, 20, 7, 50);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (29, 21, 2, 60);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (30, 22, 6, 12);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (31, 23, 7, 50);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (32, 24, 4, 20);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (33, 25, 1, 120);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (34, 26, 1, 100);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (35, 27, 11, 20);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (36, 28, 2, 80);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (37, 29, 7, 50);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (38, 30, 4, 60);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (39, 31, 8, 40);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (40, 32, 7, 50);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (41, 33, 6, 20);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (42, 34, 12, 20);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (43, 35, 11, 30);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (44, 36, 11, 15);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (45, 37, 4, 55);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (46, 38, 4, 60);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (47, 39, 1, 100);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (48, 40, 1, 120);
INSERT INTO SYSTEM.MSPR_DETAIL_DEMANDE_DECHET (ID, ID_DEMANDE_ENLEVEMENT, ID_DECHET, QUANTITE) VALUES (49, 41, 1, 15);