create table MSPR_JOURNAL_DEMANDES_A_TRAITER
(
    ID         NUMBER generated as identity
        constraint MSPR_JOURNAL_DEMANDES_A_TRAITER_PK
            primary key,
    ID_DEMANDE NUMBER(5) not null
)
/

INSERT INTO SYSTEM.MSPR_JOURNAL_DEMANDES_A_TRAITER (ID, ID_DEMANDE) VALUES (33, 43);
INSERT INTO SYSTEM.MSPR_JOURNAL_DEMANDES_A_TRAITER (ID, ID_DEMANDE) VALUES (34, 42);