create table MSPR_CENTRE_TRAITEMENT
(
    ID         NUMBER(5)    not null
        constraint PK_CENTRE_TRAITEMENT
            primary key,
    ID_ADRESSE NUMBER(5)    not null
        constraint FK_ADRESSE_CENTRE_TRAITEMENT
            references MSPR_ADRESSE,
    NOM        VARCHAR2(20) not null
)
/

INSERT INTO SYSTEM.MSPR_CENTRE_TRAITEMENT (ID, ID_ADRESSE, NOM) VALUES (1, 1, 'Centre Bourdin');
INSERT INTO SYSTEM.MSPR_CENTRE_TRAITEMENT (ID, ID_ADRESSE, NOM) VALUES (2, 2, 'Prorecycle');
INSERT INTO SYSTEM.MSPR_CENTRE_TRAITEMENT (ID, ID_ADRESSE, NOM) VALUES (3, 3, 'Revie');
INSERT INTO SYSTEM.MSPR_CENTRE_TRAITEMENT (ID, ID_ADRESSE, NOM) VALUES (4, 4, 'Deuxième Vie');
INSERT INTO SYSTEM.MSPR_CENTRE_TRAITEMENT (ID, ID_ADRESSE, NOM) VALUES (5, 5, 'Neo');