create table MSPR_DEPOT
(
    ID                   NUMBER(5) not null
        constraint PK_DEPOT
            primary key,
    ID_TOURNEE           NUMBER(5) not null
        constraint FK_TOURNEE_DEPOT
            references MSPR_TOURNEE,
    ID_CENTRE_TRAITEMENT NUMBER(5) not null
        constraint FK_CENTRE_TRAITEMENT_DEPOT
            references MSPR_CENTRE_TRAITEMENT
)
/

INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (1, 1, 1);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (2, 1, 1);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (3, 1, 1);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (4, 1, 4);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (5, 1, 4);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (6, 1, 5);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (7, 2, 2);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (8, 2, 2);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (9, 2, 2);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (10, 2, 2);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (11, 3, 1);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (12, 3, 3);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (13, 3, 1);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (14, 3, 3);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (15, 4, 2);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (16, 4, 2);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (17, 4, 2);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (18, 4, 2);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (19, 4, 2);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (20, 4, 4);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (21, 5, 3);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (22, 5, 3);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (23, 5, 3);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (24, 5, 3);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (25, 6, 4);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (26, 6, 4);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (27, 6, 4);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (28, 6, 4);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (29, 6, 4);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (30, 7, 3);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (31, 7, 3);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (32, 7, 5);
INSERT INTO SYSTEM.MSPR_DEPOT (ID, ID_TOURNEE, ID_CENTRE_TRAITEMENT) VALUES (33, 7, 5);