create table MSPR_CAMION
(
    ID           NUMBER(5)              not null
        constraint PK_CAMION
            primary key,
    ID_SITE      NUMBER(5)              not null
        constraint FK_SITE_CAMION
            references MSPR_SITE,
    NO_MATRICULE VARCHAR2(50)           not null,
    DATE_ACHAT   DATE default (sysdate) not null,
    MODELE       VARCHAR2(30)           not null,
    MARQUE       VARCHAR2(20)           not null,
    MAX_PLACES   NUMBER(5)              not null
)
/

INSERT INTO SYSTEM.MSPR_CAMION (ID, ID_SITE, NO_MATRICULE, DATE_ACHAT, MODELE, MARQUE, MAX_PLACES) VALUES (1, 1, '236CKV95', TO_DATE('2000-12-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Sprinter', 'Mercedes', 5);
INSERT INTO SYSTEM.MSPR_CAMION (ID, ID_SITE, NO_MATRICULE, DATE_ACHAT, MODELE, MARQUE, MAX_PLACES) VALUES (2, 1, '257DEF95', TO_DATE('2000-12-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Sprinter', 'Mercedes', 10);
INSERT INTO SYSTEM.MSPR_CAMION (ID, ID_SITE, NO_MATRICULE, DATE_ACHAT, MODELE, MARQUE, MAX_PLACES) VALUES (3, 1, '357BAS95', TO_DATE('2004-04-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Master', 'Renault', 15);
INSERT INTO SYSTEM.MSPR_CAMION (ID, ID_SITE, NO_MATRICULE, DATE_ACHAT, MODELE, MARQUE, MAX_PLACES) VALUES (4, 1, '763OPE95', TO_DATE('2004-04-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Master', 'Renault', 20);
INSERT INTO SYSTEM.MSPR_CAMION (ID, ID_SITE, NO_MATRICULE, DATE_ACHAT, MODELE, MARQUE, MAX_PLACES) VALUES (5, 1, '124FAK95', TO_DATE('2006-09-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ZE', 'Renault', 25);
INSERT INTO SYSTEM.MSPR_CAMION (ID, ID_SITE, NO_MATRICULE, DATE_ACHAT, MODELE, MARQUE, MAX_PLACES) VALUES (6, 1, '658SQL95', TO_DATE('2010-10-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'TGL', 'Man', 30);
INSERT INTO SYSTEM.MSPR_CAMION (ID, ID_SITE, NO_MATRICULE, DATE_ACHAT, MODELE, MARQUE, MAX_PLACES) VALUES (7, 1, '532DFC95', TO_DATE('2010-10-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'TGL', 'Man', 35);
INSERT INTO SYSTEM.MSPR_CAMION (ID, ID_SITE, NO_MATRICULE, DATE_ACHAT, MODELE, MARQUE, MAX_PLACES) VALUES (8, 1, '602LKS95', TO_DATE('2010-10-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'TGL', 'Man', 40);